name: Latest portfolio
on:
  schedule:
      # Runs at the end of every week
      - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:     
  job_1:
    name: update-index-with-project
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: kaustubhgupta/PortfolioFy@main
          with:
            gh_token: ${{ secrets.TOKEN }}
            stats_choice: 2
            blogs: True
            theme: 2
            hackathons: True
            social_links: 'https://www.linkedin.com/in/kaustubh-gupta/, https://twitter.com/Kaustubh1828, https://medium.com/@kaustubhgupta1828, https://dev.to/kaustubhgupta, https://stackoverflow.com/users/14681298/kaustubh'
  
        - uses: test-room-7/action-update-file@v1
          with:
            file-path: |
              index.html
            commit-msg: index file added
            github-token: ${{ secrets.TOKEN }}
