name: Updating Index
on:
  schedule:
      # Runs at the end of every day
      - cron: '0 0 * * *'
  workflow_dispatch:

jobs:     
  job_1:
    name: update-index
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: kaustubhgupta/PortfolioFy@dev
          with:
            gh_token: ${{ secrets.TOKEN }}
            stats_choice: 2
            blogs: True
            theme: 2
            hackathons: True
            social_links: "https://www.linkedin.com/in/kaustubh-gupta/, https://twitter.com/Kaustubh1828, https://medium.com/@kaustubhgupta1828"
            allow_footer: False
            current_repo_path: ${{ github.workspace }}
